apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  role: "piercuta-dev-karpenter-node-role"
  amiSelectorTerms:
    - alias: "al2023@v20250620"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "piercuta-dev-eks-cluster" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "piercuta-dev-eks-cluster" # replace with your cluster name