apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-auth-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # le plus tôt possible
spec:
  project: default
  source:
    repoURL: https://github.com/Piercuta/eks-git-ops.git
    targetRevision: main
    path: clusters/config/
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    # ❌ Ne surtout pas automatiser sans précaution
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-bootstrap
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/Piercuta/eks-git-ops.git
    targetRevision: main
    path: infrastructure/base/argocd
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # déployé avant les apps
spec:
  project: default
  source:
    repoURL: https://github.com/Piercuta/eks-git-ops.git
    targetRevision: main
    path: infrastructure/dev
    kustomize:
      namespace: kube-system
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
