apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-bootstrap
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/ton-org/repo-gitops
    targetRevision: main
    path: infrastructure/base/argocd
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # déployé avant les apps
spec:
  project: default
  source:
    repoURL: https://github.com/ton-org/repo-gitops
    targetRevision: main
    path: infrastructure/dev
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
