apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-sa
  namespace: fastapi
  labels:
    app: fastapi
    project: ${PROJECT_NAME}
    env: ${ENVIRONMENT}
  annotations:
    eks.amazonaws.com/role-arn: ${SERVICE_ACCOUNT_ROLE_ARN} # <-- ARN du rôle IAM lié (facultatif si tu fais de l'IRSA)