apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: fastapi-node-class
  labels:
    app: fastapi
    env: ${ENV_NAME}
    project: ${PROJECT_NAME}
spec:
  role: ${KARPENTER_NODE_ROLE_NAME}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery-fastapi: ${CLUSTER_NAME}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery-fastapi: ${CLUSTER_NAME}
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@v20250620
  tags:
    Name: ${PROJECT_NAME}-${ENV_NAME}-fastapi-node
    App: fastapi
    Env: ${ENV_NAME}
    ManagedBy: karpenter