apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: aws-load-balancer-controller
    repo: https://aws.github.io/eks-charts
    version: 1.8.2
    releaseName: alb
    namespace: kube-system
    valuesFile: values.yaml
