apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  namespace: kube-system
  labels:
    app: karpenter
  name: karpenter-node-class
spec:
  role: piercuta-dev-karpenter-node-role
  tags:
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: piercuta-dev-eks-cluster
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: piercuta-dev-eks-cluster
