apiVersion: karpenter.k8s.aws/v1
kind: NodePool
metadata:
  name: karpenter-node-pool
  namespace: kube-system
spec:
  template:
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
