apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  labels:
    app: karpenter
  name: karpenter-node-class
spec:
  role: ${KARPENTER_NODE_ROLE_NAME}
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: piercuta-dev-eks-cluster
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: piercuta-dev-eks-cluster
  tags:
    EnvName: dev
    ProjectName: piercuta
