apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  install:
    crds: CreateReplace
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: karpenter
    namespace: flux-system
  values:
    settings:
      clusterName: "piercuta-dev-eks-cluster"
      interruptionQueue: "piercuta-dev-eks-cluster"
    serviceAccount:
      create: true
      name: karpenter
    replicas: 1
    controller:
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi