apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  install:
    crds: CreateReplace
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: karpenter
    namespace: flux-system
  values:
    settings:
      clusterName: "piercuta-dev-eks-cluster"
      clusterEndpoint: "https://4499E6BFEAA0D4BCCD96C10D655309DE.gr7.eu-west-1.eks.amazonaws.com"
    serviceAccount:
      create: false
      name: karpenter-sa
    replicas: 1
    controller:
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi