# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: karpenter
#   namespace: karpenter
# spec:
#   chart:
#     spec:
#       chart: karpenter
#       version: 1.5.0  # adapte selon la version désirée disponible dans le repo
#       sourceRef:
#         kind: HelmRepository
#         name: karpenter
#         namespace: flux-system
#   interval: 5m
#   targetNamespace: karpenter
#   install:
#     crds: createReplace
#   values:
#     settings:
#       clusterName: "piercuta-dev-eks-cluster"   # mets le nom de ton cluster
#       clusterEndpoint: "https://003E83B19B1984FBE1348A7240F2C3B5.gr7.eu-west-1.eks.amazonaws.com"  # endpoint de ton cluster EKS
#       serviceAccount:
#         name: karpenter-sa
#         create: false
#       replicas: 1
#       controller:
#         resources:
#           requests:
#             cpu: 1
#             memory: 1Gi
#           limits:
#             cpu: 1
#             memory: 1Gi
  

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  install:
    crds: createReplace
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: karpenter
    namespace: flux-system
  values:
    settings:
      clusterName: "<TON_CLUSTER_EKS>"
      clusterEndpoint: "<ENDPOINT_API_EKS>"
    serviceAccount:
      create: false
      name: karpenter-sa
    replicas: 1
    controller:
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
