settings:
  clusterName: "piercuta-dev-eks-cluster"
  interruptionQueue: "piercuta-dev-eks-cluster"
serviceAccount:
  create: true
  name: karpenter
replicas: 2
controller:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi