apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: aws-load-balancer-controller
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  interval: 5m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.8.2"
      sourceRef:
        kind: HelmRepository
        name: alb-controller-repo
        namespace: flux-system
      interval: 1m
      install:
        crds: CreateReplace
  values:
    clusterName: piercuta-dev-eks-cluster  # Remplace par ton cluster
    vpcId: vpc-07b7cfdc6b2c7bf05
    serviceAccount:
      create: false
      name: aws-load-balancer-controller-sa  # Le ServiceAccount qui porte le rôle IAM
    version: "1.8.2"