apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  interval: 5m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.8.2"
      sourceRef:
        kind: HelmRepository
        name: alb-controller-repo
        namespace: flux-system
      interval: 1m
  install:
    crds: CreateReplace    
  values:
    clusterName: piercuta-dev-eks-cluster  # Remplace par ton cluster
    vpcId: vpc-026fb01ce2dc9defe
    serviceAccount:
      create: true
      name: aws-load-balancer-controller # Le ServiceAccount qui porte le rôle IAM
