apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  labels:
    app: fastapi
  name: fastapi-node-class
spec:
  role: piercuta-dev-karpenter-node-role
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery-fastapi: piercuta-dev-eks-cluster
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery-fastapi: piercuta-dev-eks-cluster
