apiVersion: v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: fastapi
spec:
  replicas: ${DESIRED_REPLICAS}
  template:
    spec:
      containers:
      - name: fastapi
        image: ${IMAGE_URL}
        resources:
          requests:
            cpu: ${CPU_CAPACITY}
            memory: ${MEM_CAPACITY}
          limits:
            cpu: ${CPU_CAPACITY}
            memory: ${MEM_CAPACITY}
