apiVersion: v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: fastapi
spec:
  template:
    spec:
      containers:
      - image: 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/ecs/fastapi_app:latest
        name: fastapi
        resources:
          limits:
            cpu: "2"
            memory: "750Mi"
          requests:
            cpu: "2"
            memory: "750Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
