apiVersion: v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: fastapi
spec:
  template:
    spec:
      containers:
      - image: curlimages/curl:latest
        name: fastapi
        resources:
          limits:
            cpu: "2"
            memory: "750Mi"
          requests:
            cpu: "2"
            memory: "750Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
