apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/Piercuta/eks-git-ops.git
    targetRevision: main
    path: cluster-config/aws-load-balancer-controller
    helm:
      valueFiles:
        - values.yaml  # ou un autre fichier de valeurs si tu veux en surcharger
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
