apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-pool
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/Piercuta/eks-git-ops.git  # adapte avec ton repo
    targetRevision: main
    path: services/karpenter
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
