apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: karpenter
    repoURL: public.ecr.aws/karpenter
    targetRevision: 1.5.2
    helm:
      values: |
        settings:
          clusterName: "piercuta-dev-eks-cluster"
          interruptionQueue: "piercuta-dev-eks-cluster"
        serviceAccount:
          create: true
          name: karpenter
        replicas: 2
        controller:
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
