apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: fastapi
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
        fastapi.com/node-type: fastapi
    spec:
      nodeSelector:
        fastapi.com/node-type: fastapi
      serviceAccountName: fastapi-sa
      containers:
      - name: fastapi
        envFrom:
        - configMapRef:
            name: fastapi-config
        ports:
        - containerPort: 8000