apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: fastapi-node-class
  labels:
    app: fastapi
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@v20250620
  tags:
    Name: fastapi-node
    App: fastapi
    ManagedBy: karpenter