apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cm.yaml
  - deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - ec2nodeclass.yaml
  - nodepool.yaml
  - namespace.yaml
  - service.yaml
  - serviceaccount.yaml
