apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
  - repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: 1.5.2
    helm:
      values: |
        controller:
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
        replicas: 2
        serviceAccount:
          create: true
          name: karpenter
        settings:
          clusterName: piercuta-prod-eks-cluster
          interruptionQueue: piercuta-prod-eks-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
